services:
    api.kernel_request_listener:
        class: ApiBundle\Service\KernelListener
        arguments: ['uploads']
        tags:
            - { name: kernel.event_listener, event: kernel.request, method: onKernelRequest }

    app.mailer:
        class: AppBundle\Adapter\Mailer\Mandrill\MandrillMailer
        arguments: ['@logger', '%mailer_api_key%', '%mailer_disable_delivery%']
        tags:
            - { name: monolog.logger, handler: mailer }

    app.cache:
        class: AppBundle\Adapter\Cache\Database\DatabaseCache
        arguments: ['@doctrine', "AppBundle\\Entity\\Cache"]